- name: Clone dircolors-solarized using ghq
  shell: |
    eval "$({{ ansible_facts.env.HOME }}/.local/bin/mise activate bash)"
    ghq get https://github.com/seebi/dircolors-solarized.git
  args:
    executable: /bin/bash
