- name: Do not require sudo password to restart avahi-daemon
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^{{ ansible_facts.env.USER }} ALL=NOPASSWD: /usr/bin/systemctl restart avahi-daemon'
    line: '{{ ansible_facts.env.USER }} ALL=NOPASSWD: /usr/bin/systemctl restart avahi-daemon'
    validate: 'visudo -cf %s'
  become: true

- name: Do not require sudo password to restart NetworkManager
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^{{ ansible_facts.env.USER }} ALL=NOPASSWD: /usr/bin/systemctl restart NetworkManager'
    line: '{{ ansible_facts.env.USER }} ALL=NOPASSWD: /usr/bin/systemctl restart NetworkManager'
    validate: 'visudo -cf %s'
  become: true
